In [2]:
import numpy as np
import pandas as pd
import random
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import GridSearchCV

In [12]:
bank = pd.read_csv("bank_normalized_final.csv", header=None)

In [13]:
bank.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,age,campaign,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,education_un,job_un,...,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,y_yes
1,56,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,57,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
3,37,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
4,40,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0

In [14]:
bank.columns = bank.iloc[0]

In [24]:
bank

,age,campaign,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,education_un,job_un,...,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,y_yes
0,age,campaign,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,education_un,job_un,...,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,y_yes
1,56,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,57,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
3,37,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
4,40,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41184,73,1,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,0,1,0,1
41185,46,1,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,0,1,0,0
41186,56,2,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,0,1,0,0
41187,44,1,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,0,1,0,1
41188,74,3,1,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,1,0,0,0

In [25]:
bank = bank.drop(bank.index[0])

In [26]:
bank

,age,campaign,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,education_un,job_un,...,month_sep,day_of_week_fri,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_failure,poutcome_nonexistent,poutcome_success,y_yes
1,56,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,57,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
3,37,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
4,40,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
5,56,1,0,1.1,93.994,-36.4,4.857,5191.0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41184,73,1,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,0,1,0,1
41185,46,1,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,0,1,0,0
41186,56,2,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,0,1,0,0
41187,44,1,0,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,0,1,0,1
41188,74,3,1,-1.1,94.767,-50.8,1.028,4963.6,0,0,...,0,1,0,0,0,0,1,0,0,0

In [27]:
bank.columns.values

array(['age', 'campaign', 'previous', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'education_un',
       'job_un', 'housing_un', 'loan_un', 'pdays_missing',
       'pdays_greater_15', 'pdays_bet_5_15', 'job_admin.',
       'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'marital_divorced', 'marital_married', 'marital_unknown',
       'education_basic.4y', 'education_basic.6y', 'education_basic.9y',
       'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'default_unknown', 'default_yes', 'housing_yes', 'loan_yes',
       'contact_telephone', 'month_apr', 'month_aug', 'month_dec',
       'month_jul', 'month_jun', 'month_mar', 'month_may', 'month_nov',
       'month_oct', 'month_sep', 'day_of_week_fri', 'day_of_week_mon',
       'day_of_week_thu', 'day_of_week_tue', 'day_of_week_wed',
       'poutcome_failure', 'poutcome_nonexistent', 'poutcome_success',
       'y_yes'], dtype=object)

In [29]:
class RegularizedLogisticRegressionModel:
    def __init__(self, lr=0.01, num_iter=100000, fit_intercept=True,lagrange_mul=1):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
        self.lagrange_mul=lagrange_mul
    
    def add_intercept(self, X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    def sigmoid(self, z):        
        return 1 / (1 + np.exp(-z))
        
    def grad(self, X, y,w,w0,lagrange_mul):
        N=X.shape[0]
        #print(w0)
        tmp=0
        tmp2=0
        
        for i in range(N):
            z=X[i].dot(w)+w0
            f_x_i=self.sigmoid(z)
            tmp +=f_x_i-y[i]
            #print(tmp)
            tmp3=np.array([X[i]])
            #print(tmp3.shape)
            tmp2 +=(tmp3.T).dot((f_x_i-y[i]))
        
        tmp2=np.array([tmp2])
        tmp2=tmp2.T
        
        w0=w0-(self.lr/N)*(tmp)
        w=w*(1-(self.lr*lagrange_mul)/N) - (self.lr/N)*(tmp2)
        return w,w0 
    
    def predict_prob(self, X,w):
        if self.fit_intercept:
            X = self.add_intercept(X)
        #w=w/X.shape[0]
        z=np.dot(X, w)
        
        result=self.sigmoid(z)
        #print(result)
        return result
    
    def predict(self, X, threshold,w):
        return self.predict_prob(X,w) >= threshold
    
    def loss(self, f_x, y,w,lagrange_mul):
        n=w.shape[0]
        N=f_x.shape[0]
        
        tmp=0
        tmp2=0
        for i in range(1,n):
            tmp +=w[i]**2
        for i in range(N):
            tmp2 +=y[i]*np.log(f_x[i]) + (1-y[i])*np.log(1-f_x[i])
        j_w= -tmp2+lagrange_mul*tmp       
        return j_w/N
    
    def write_prediction(self,filename,preds):
        param_file=open(filename,"w")
        for i in range(0,len(preds)):
            if(preds[i]==True):
                param_file.write(str(1))
            else:
                param_file.write(str(0))
            param_file.write("\n")
        param_file.close()
    
    def get_classifications(self,y,preds):
        preds_val=[]
        tp=0
        tn=0
        fp=0
        fn=0
        for i in range(len(preds)):
            if(preds[i] == True):
                preds_val.append(1)
            else:
                preds_val.append(0)
            if(preds_val[i] ==y[i]):
                if(preds_val[i]==1):
                    tp=tp+1
                else:
                    tn=tn+1
            else:
                if(preds_val[i]==1):
                    fp=fp+1
                else:
                    fn=fn+1  
        
        return tp,tn,fp,fn   
    def get_perf_params(self,tp,tn,fp,fn):
        sensitivity=0
        specificity=0
        precision=0
        f_measure=0
        if(tp+fn !=0):
            sensitivity=tp/(tp+fn)
        if(tn+fp !=0):
            specificity=tn/(tn+fp)
        if(tp+fp !=0):
            precision=tp/(tp+fp)
        if(precision + sensitivity !=0):
            f_measure=(2*precision*sensitivity)/(precision+sensitivity)
        accuracy=(tp+tn)/(tp+tn+fp+fn)
        
        return accuracy,sensitivity,specificity,precision,f_measure

In [30]:
N,n = bank.shape
print(N)
data = bank.iloc[1:N,:]
arr = data

41188

In [31]:
arr = data.to_numpy(dtype = float)

In [32]:
arr.shape

(41187, 60)

In [33]:
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib notebook 
#to enable interactivity and rotation of 3D figures 
from mpl_toolkits.mplot3d import Axes3D
from sklearn.model_selection import train_test_split

data = arr
log_model = RegularizedLogisticRegressionModel(0.6,10000,True,2)


print(data.shape)
N=arr.shape[0]
n=arr.shape[1]
X=arr[:,0:n-1]
y=arr[:,n-1:n]
    
    
mean_X=np.mean(X,axis=0)
std_X=np.std(X,axis=0)    
X=(X-mean_X)/(std_X)    
neg_vals=0
for i in range(y.size):
    if(y[i] == -1):
        y[i]=0
        neg_vals +=1
        
w_old=np.zeros((n-1,1))
w0_old=0
norm=1000*10000
w_new=w_old
iteration_no=0
while(norm > 1e-3 and iteration_no < log_model.num_iter):
    w_new,w0_new=log_model.grad(X,y,w_old,w0_old,0.1)
    norm=np.linalg.norm(w_new-w_old)
    w_old=w_new
    w0_old=w0_new
    iteration_no +=1

w_new=np.vstack((w0_new,w_new))
preds = log_model.predict(X,0.5,w_new)
tp,tn,fp,fn=log_model.get_classifications(y,preds)
   
accuracy,sensitivity,specificity,precision,f_measure=log_model.get_perf_params(tp,tn,fp,fn)
    
print("tp=",tp)
print("tn=",tn)
print("fp=",fp)    
print("fn=",fn)
    
print("Accuracy=",accuracy)
print("Sensitivity=",sensitivity)
print("Specificity=",specificity)
print("Precision=",precision)
print("F_measure=",f_measure)

(41187, 60)
tp= 1055
tn= 36035
fp= 512
fn= 3585
Accuracy= 0.9005268652730231
Sensitivity= 0.2273706896551724
Specificity= 0.9859906421867732
Precision= 0.6732610082961072
F_measure= 0.33993877879813117

In [34]:
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib notebook 
#to enable interactivity and rotation of 3D figures 
from mpl_toolkits.mplot3d import Axes3D
import math
from scipy.spatial import distance

class KNN:
    def __init__(self):
        pass
    def seperate_classes(self,X,y):
        tmp=y.tolist()
        flattened = [val for sublist in tmp for val in sublist]
        class_names = list(set(flattened))
        k=len(class_names)
        print("No of classes:=",k)
        class_list=[]
        for i in range(len(class_names)):
            tmplist=[]
            class_list.append(tmplist)
        print(class_names)
        for i in range(y.size):
            for j in range(len(class_names)):
                if(y[i] == class_names[j]):
                    class_list[j].append(X[i])
                    break
                
        for i in range(len(class_names)):
            class_list[i]=np.asarray(class_list[i])
           
        return class_names,class_list
    
    def find_co_variance(self,X,y,mean_list,class_names):
        class_list=[]
        k=len(class_names)
        n=X.shape[1]
        t=np.zeros((k,n,1))
        t_mean=np.zeros((k,n,1))
        
        cov_mat_com=np.zeros((n,n))
       
        #print(t_mean.shape)
        
        class_cnt=[]
        for i in range(k):
            t_mean[i,:,0]=mean_list[i]
            class_cnt.append(0)
       
        for i in range(X.shape[0]):
            for j in range(len(class_names)):
                if(y[i] == class_names[j]):
                    t1=np.array([X[i,:]])
                    tmp=(t1.T-t_mean[j]).dot((t1.T-t_mean[j]).T)
                    #tmp=(X[i,:].T-t_mean[j]).dot((X[i,:].T-t_mean[j]).T)
                    cov_mat_com=cov_mat_com+tmp
                    #tmp=(X[i,:]-t_mean[j]).dot((X[i,:]-t_mean[j]).T)
                    break
        cov_mat_com=cov_mat_com/(X.shape[0])
        return cov_mat_com
                
    def find_distance(self,X,x,dist_type,y,mean_list,class_names):
        N=X.shape[0]
        n=X.shape[1]
        dist_list=[]
        #sigma=self.find_co_variance(X,y,mean_list,class_names)
        #sigma_inv=np.linalg.inv(sigma)
        for i in range(N):
            if(dist_type=='Euclidean'):
                val=abs(((X[i]-x).T).dot((X[i]-x)))
                dist=math.sqrt(val)
            #elif(dist_type=="Mahalonabis"):
                
                #dist=distance.mahalanobis(X[i],x,sigma_inv)
            elif(dist_type=='Manhattan'):
                dist=0
                for j in range(n):
                    dist +=abs(X[i,j]-x[j])
            dist_list.append(dist)
                
        return dist_list
    def get_mean(self,X):
        return np.mean(X,axis=0)
    
    def predict(self,y,dist_list,class_names,k):
        dist_list,y_tmp = zip(*sorted(zip(dist_list, y)))
        
        neighbour_cnt=[]
        for i in range(len(class_names)):
            neighbour_cnt.append(0)
        
        for i in range(1,k):
            for j in range(len(class_names)):
                if(y_tmp[i]==class_names[j]):
                    neighbour_cnt[j] +=1
                    break
        pred_class=np.argmax(neighbour_cnt)
        return class_names[pred_class]
                    
#         return preds
    
    def write_prediction(self,filename,preds):
        param_file=open(filename,"w")
        for i in range(0,len(preds)):
            param_file.write(str(preds[i]))
            param_file.write("\n")
        param_file.close()
    
    def get_classifications(self,y,preds):
        preds_val=[]
        correct=0
        incorrect=0
        tp=0
        tn=0
        fp=0
        fn=0
        
        for i in range(len(preds)):
            if(preds[i] ==y[i]):
                if(y[i]==1):
                    tp +=1
                else:
                    tn+=1
            else:
                if(y[i]==1):
                    fn +=1
                else:
                    fp+=1
        return tp,tn,fp,fn   
    def get_perf_params(self,tp,tn,fp,fn):
        sensitivity=0
        specificity=0
        precision=0
        f_measure=0
        if(tp+fn !=0):
            sensitivity=tp/(tp+fn)
        if(tn+fp !=0):
            specificity=tn/(tn+fp)
        if(tp+fp !=0):
            precision=tp/(tp+fp)
        if(precision + sensitivity !=0):
            f_measure=(2*precision*sensitivity)/(precision+sensitivity)
        accuracy=(tp+tn)/(tp+tn+fp+fn)
        
        return accuracy,sensitivity,specificity,precision,f_measure
    
    def plot_ROC(self,neg_specificity_list,sensitivity_list):
        plt.title('Receiver Operating Characterestic Curve');
        plt.xlabel('1-Specificity')
        plt.ylabel('Sensitivity')
        plt.xlim(-0.1,1.05)
        plt.ylim(-0.1,1.05)
        plt.plot(neg_specificity_list,sensitivity_list,label='ROC',color='r')
        plt.show()
        
    
    def cross_validation(self,X,y,class_names,mean_list,k_min,k_max,step_size):
        
        N=X.shape[0]
        n=X.shape[1]
        #print(N,n)
        accuracy_list=[]
        sensitivity_list=[]
        precision_list=[]
        neg_specificity_list=[]
        f_measure_list=[]
        
        k_arr=[]
        for k_val in range(k_min,k_max,step_size):  
            print("k=",k_val)
            preds=[]
            k_arr.append(k_val)
            k_int=int(k_val)
            for i in range(N):
                dist_list=knn.find_distance(X,X[i],"Euclidean",y,mean_list,class_names)
                #dist_list=knn.find_distance(X,X[i],"Mahalonabis",y,mean_list,class_names)
                #dist_list=knn.find_distance(X,X[i],"Manhattan",y,mean_list,class_names)                
                preds.append(knn.predict(y,dist_list,class_names,k_int))
                          
            
            tp,tn,fp,fn=self.get_classifications(y,preds)
            accuracy,sensitivity,specificity,precision,f_measure=self.get_perf_params(tp,tn,fp,fn)
            accuracy_list.append(accuracy)
            f_measure_list.append(f_measure)
            sensitivity_list.append(sensitivity)
            neg_specificity_list.append(1-specificity)
            
        index=f_measure_list.index(max(f_measure_list))
        return k_arr[index],max(f_measure_list),neg_specificity_list,sensitivity_list

In [185]:
knn=KNN()
N=arr.shape[0]
n=arr.shape[1]
X=arr[:,0:n-1]
y=arr[:,n-1:n]


for i in range(y.size):
        if(y[i] == -1):
            y[i]=0
class_names,class_list=knn.seperate_classes(X,y)

print(class_names)
mean_list=[]
for i in range(len(class_names)):
    tmplist=[]
    mean_list.append(tmplist)
    mean_list[i]=knn.get_mean(class_list[i])

sigma=knn.find_co_variance(X,y,mean_list,class_names)
preds=[]
k_min=1
k_max=int(N/100)
step_size=5
#k_val,max_f_measure,neg_specificity_list,sensitivity_list=knn.cross_validation(X,y,class_names,mean_list,k_min,k_max,step_size)
#print("k for Maximum F-measure is:",k_val)
#print("MAximum F-measure is:",max_f_measure)
for i in range(N):
    dist_list=knn.find_distance(X,X[i],"Euclidean",y,mean_list,class_names)
    preds.append(knn.predict(y,dist_list,class_names,100))
    #dist_list=knn.find_distance(X,X[i],"Mahalonabis",y,mean_list,class_names)
    #dist_list=knn.find_distance(X,X[i],"Manhattan",y,mean_list,class_names)
 
    #preds.append(knn.predict(y,dist_list,class_names,int(k_val)))
    

tp,tn,fp,fn=knn.get_classifications(y,preds)
accuracy,sensitivity,specificity,precision,f_measure=knn.get_perf_params(tp,tn,fp,fn)

print("tp=",tp)
print("tn=",tn)
print("fp=",fp)
print("fn=",fn)

print("Accuracy=",accuracy)
print("Sensitivity=",sensitivity)
print("Specificity=",specificity)
print("Precision=",precision)
print("F_measure=",f_measure)

#knn.plot_ROC(neg_specificity_list,sensitivity_list)

No of classes:= 2
[0.0, 1.0]
[0.0, 1.0]
tp= 753
tn= 35966
fp= 582
fn= 3887
Accuracy= 0.8914975235505487
Sensitivity= 0.1622844827586207
Specificity= 0.9840757360183868
Precision= 0.5640449438202247
F_measure= 0.2520502092050209